---
- name: Instance Cleanup
  hosts: all
  gather_facts: false
  vars_files:
    - generated_vars/converge.yml
  tasks:
    - include_tasks: tasks/artifacts_stats.yml
    - name: Remove artifact
      file:
        path: "{{ item.stat.path }}"
        state: absent
      when: item.stat.exists
      with_items: "{{ artifacts_stats.results }}"
    - name: Remove container
      docker_container:
        name: "{{ docker_volume_for_container }}"
        state: absent
    - name: Remove volume
      docker_volume:
        name: "{{ docker_volume_name }}"
        state: absent

- name: Local Cleanup
  hosts: localhost
  gather_facts: false
  vars_files:
    - vars/generate.yml
  tasks:
    - name: Remove converge vars
      file:
        path: "{{ converge_vars_filepath }}"
        state: absent
