---
- name: Verify
  hosts: all
  gather_facts: false
  vars_files:
    - generated_vars/converge.yml
  tasks:
    - name: "Wait for container '{{ container_name }}' to stop"
      docker_container_info:
        name: "{{ container_name }}"
      register: inst
      retries: "{{ 60 * crontime_minutes_offset | int }}"
      delay: 1
      until: not inst.exists or not inst.container.State.Running
      failed_when: not inst.exists or inst.container.State.Running

    - include_tasks: tasks/artifacts_stats.yml
    - name: Expect that files exist
      assert:
        that: item.stat.exists
      with_items: "{{ artifacts_stats.results }}"
